services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVzGhP5YpHBXUvZG2mwGhByN19GAY0IpRNgF7vbecyoB+/73Oo3Hu7AKPGasWK5Fe1VXSP266IwHTNRZs/FalW/u5S0bEpDEqxMsECFT50y+8IJ4OhWQpVqTOq09VzHtUdmKCUtE/b/MxSzSqsXnU7zkELLo0xRCXrdTE1P6whpIkhMiq4rqzvF0WA2anjGFvrjOpT0UjOxF0vrTpeYPU7i60OyIwre3fFmdKCAQJBb8+JapXwG1sEm3/+BdHV0ZsxSXEEzor5LljBJEWIyfmacAhIT5QLInYWphtd2GjHTopr9OKLL2Jc4cyXrFRSsM0S+gYYH7GTPL0rXu5E+HWH root@b76e4b1bce66
volumes:
  jenkins_home: